model_params:
  common_params:
    num_kp: 10  # Reduced from 15 to 10
    image_channel: 3                    
    feature_channel: 24  # Reduced from 32
    estimate_jacobian: False
  kp_detector_params:
     temperature: 0.2  # Increased for smoother keypoints
     block_expansion: 24  # Reduced from 32
     max_features: 768  # Reduced from 1024
     scale_factor: 0.5  # Increased from 0.25 for faster processing
     num_blocks: 4  # Reduced from 5
     reshape_channel: 12288  # Reduced from 16384
     reshape_depth: 16
  he_estimator_params:
     block_expansion: 64            
     max_features: 2048
     num_bins: 66
  generator_params:
    block_expansion: 48  # Reduced from 64
    max_features: 384  # Reduced from 512
    num_down_blocks: 1  # Reduced from 2
    reshape_channel: 24  # Reduced from 32
    reshape_depth: 16
    num_resblocks: 4  # Reduced from 6
    estimate_occlusion_map: False  # Disabled for better performance
    dense_motion_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 5
      reshape_depth: 16
      compress: 4
  discriminator_params:
    scales: [1]
    block_expansion: 32                 
    max_features: 512
    num_blocks: 4
    sn: True
  mapping_params:
      coeff_nc: 70
      descriptor_nc: 1024
      layer: 3
      num_kp: 15
      num_bins: 66

